-- ==============================================================================
-- THE DAILY DRAFT - PRODUCTION RELATIONAL DATABASE SCHEMA & EXPANDED DATA
-- Features:
-- 1. Full Referential Integrity: profiles -> posts, comments, likes
-- 2. Unique Constraints: 1 like per user per article
-- 3. PostgreSQL Trigger: Automatically keeps posts.likes synced with likes table
-- 4. Expanded Community: 16 Profiles, 10 Rich Articles, 25 Comments, 56 Likes
-- ==============================================================================

-- 1. Cleanly reset existing tables, triggers, and functions
DROP TRIGGER IF EXISTS trigger_sync_post_like_count ON public.likes CASCADE;
DROP FUNCTION IF EXISTS public.sync_post_like_count() CASCADE;
DROP TABLE IF EXISTS public.likes CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.posts CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 2. Profiles (Users) Table
CREATE TABLE public.profiles (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::TEXT, now()) NOT NULL
);

-- 3. Posts Table
CREATE TABLE public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Travel' NOT NULL,
  author TEXT NOT NULL,
  author_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  excerpt TEXT,
  likes INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::TEXT, now()) NOT NULL
);

-- 4. Comments Table
CREATE TABLE public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  author_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
  author TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::TEXT, now()) NOT NULL
);

-- 5. Likes Table (Strict User-to-Post Mapping)
CREATE TABLE public.likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  user_id TEXT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::TEXT, now()) NOT NULL,
  CONSTRAINT unique_post_user_like UNIQUE (post_id, user_id)
);

-- 6. PostgreSQL Trigger: Automatically sync posts.likes with count of public.likes
CREATE OR REPLACE FUNCTION public.sync_post_like_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.posts
    SET likes = (SELECT COUNT(*) FROM public.likes WHERE post_id = NEW.post_id)
    WHERE id = NEW.post_id;
    RETURN NEW;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.posts
    SET likes = (SELECT COUNT(*) FROM public.likes WHERE post_id = OLD.post_id)
    WHERE id = OLD.post_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_sync_post_like_count
AFTER INSERT OR DELETE ON public.likes
FOR EACH ROW EXECUTE FUNCTION public.sync_post_like_count();

-- 7. Enable Row Level Security (RLS) with open public policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles access" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public posts access" ON public.posts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public comments access" ON public.comments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public likes access" ON public.likes FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- 8. EXPANDED SEED DATA (16 Users, 10 Articles, 25 Comments, 56 Likes)
-- ==============================================================================

-- A. 16 User Profiles
INSERT INTO public.profiles (id, name, email) VALUES
('user_maya', 'Maya Lin', 'maya@example.com'),
('user_sophia', 'Sophia Chen', 'sophia@example.com'),
('user_liam', 'Liam Brooks', 'liam@example.com'),
('user_emma', 'Emma Watson', 'emma@example.com'),
('user_marcus', 'Marcus Vance', 'marcus@example.com'),
('user_elena', 'Elena Rostova', 'elena@example.com'),
('user_julian', 'Julian Ross', 'julian@example.com'),
('user_clara', 'Clara Moreau', 'clara@example.com'),
('user_devon', 'Devon Patel', 'devon@example.com'),
('user_sarah', 'Sarah Jenkins', 'sarah@example.com'),
('user_alex', 'Alex Rivera', 'alex@example.com'),
('user_hannah', 'Hannah Kim', 'hannah@example.com'),
('user_oliver', 'Oliver Wright', 'oliver@example.com'),
('user_zara', 'Zara Al-Mansoor', 'zara@example.com'),
('user_theo', 'Theo Van Dijk', 'theo@example.com'),
('user_ananya', 'Ananya Sharma', 'ananya@example.com');

-- B. 10 Articles Across Travel, Cooking, Lifestyle, Books, and Technology
INSERT INTO public.posts (id, title, category, author, author_id, content, excerpt, likes, created_at) VALUES
(
  1,
  'The Art of Slow Travel: Why We Decided to Stop Rushing',
  'Travel',
  'Maya Lin',
  'user_maya',
  'Three years ago, I visited seven European cities in fourteen days. By day ten, my camera roll was overflowing with monuments I barely recalled standing in front of, and my feet were permanently sore. I had seen everything, but felt nothing.

Last autumn, I decided to do things differently. I rented a small studio apartment near the river in Florence and stayed for an entire month with no strict itinerary.

The first few days felt surprisingly uncomfortable. In modern travel culture, guilt creeps in if you are not waking up at 6:00 AM to beat tourist queues. But by day four, something shifted. I found a quiet morning bakery where the baker began nodding in recognition. I spent an entire afternoon reading in a secluded cloister garden.

Slow travel is not about seeing less; it is about feeling more. When you release the pressure of having to capture everything, the journey finally begins to belong to you.',
  'When every trip becomes a frantic race to check boxes, we miss the quiet moments that make a journey memorable.',
  0,
  now() - interval '9 days'
),
(
  2,
  'Mastering 72-Hour Sourdough: Lessons from Failed Loaves',
  'Cooking',
  'Sophia Chen',
  'user_sophia',
  'My first four attempts at sourdough yielded dense, pale bricks that could have doubled as doorstops. I blamed the starter, the flour, and my oven. In reality, the culprit was my impatience.

Bread dough is a living ecosystem of wild yeast and lactic acid bacteria. You cannot rush it, and you cannot bully it into rising on your schedule.

The breakthrough came when I stopped trying to bake bread on the same day I mixed it. Extending the bulk fermentation into a 48-to-72 hour cold retard inside the refrigerator completely changed both the crumb structure and the flavor profile.

When you pull a dark mahogany loaf from a Dutch oven at 230°C, let it rest on the wire rack for at least an hour. You will hear the crust singing—crackling softly as steam escapes. Slice it, spread salted cultured butter over the open crumb, and you will understand why humanity has revered bread for ten thousand years.',
  'Sourdough baking is less about following a rigid formula and more about understanding temperature, hydration, and patience.',
  0,
  now() - interval '8 days'
),
(
  3,
  'The Joy of Analog Mornings: 30 Days Without Screens Before 9 AM',
  'Lifestyle',
  'Liam Brooks',
  'user_liam',
  'For years, my morning began before my feet even touched the rug. I would reach for the glowing slab on the nightstand, squint through one eye, and immediately ingest world news, work emails, and social updates.

By 7:15 AM, my nervous system was already in fight-or-flight mode.

A month ago, I purchased a $12 mechanical wind-up alarm clock and banished my smartphone to a charging dock in the hallway. The rule was simple: No digital screens until 9:00 AM.

Here is what filled the void:
1. Grinding whole-bean coffee by hand with a tactile rhythm and rich aroma.
2. Writing three pages in a notebook with unfiltered thoughts.
3. Stepping outside for morning sunlight.

I did not miss a single emergency. The world was still there at 9:00 AM, but I met it with a calm, focused center instead of scattered anxiety.',
  'Reclaiming the first sixty minutes of the day from notifications and feeds completely reset my nervous system.',
  0,
  now() - interval '7 days'
),
(
  4,
  'Five Paperbacks to Carry on a Rainy Train Journey',
  'Books',
  'Emma Watson',
  'user_emma',
  'There is no reading experience quite like settling into a window seat on an intercity train with steady rain drumming against the glass. The rhythmic clack of the rails creates the perfect ambient white noise for deep immersion.

Here are five slim, atmospheric paperbacks that reward contemplation:

1. A Month in the Country by J.L. Carr — A poignant, tender novella about healing in an English village after war.
2. The Blue Afternoon by William Boyd — An atmospheric, globe-trotting mystery of memory and architecture.
3. South of the Border, West of the Sun by Haruki Murakami — Melancholic, jazz-soaked reflections on lost youth.
4. The Remains of the Day by Kazuo Ishiguro — A masterclass in restraint, dignity, and unexpressed longing.
5. In Praise of Shadows by Junichiro Tanizaki — A brief Japanese meditation on aesthetics, light, and silence.',
  'A curated list of five contemplative, atmospheric paperbacks perfect for quiet journeys by train.',
  0,
  now() - interval '6 days'
),
(
  5,
  'The Minimalist Developer: Building Software That Outlives Frameworks',
  'Technology',
  'Marcus Vance',
  'user_marcus',
  'Every six months, our industry crowns a new paradigm. We rewrite applications to adopt new bundlers, replace state libraries, and wrap standard browser capabilities in layers of unnecessary abstraction.

Yet when you look at the software that continues to function reliably decade after decade, a clear pattern emerges: simplicity wins.

Writing durable code means embracing platform primitives:
- Prefer semantic HTML over deeply nested div soup.
- Use standard CSS variables and grid systems instead of ephemeral utility generators.
- Keep state local whenever possible, and design data structures before writing handlers.

When we reduce dependencies, our systems run faster, load quicker, and remain understandable five years after the original developer moves on.',
  'Why modern software engineering needs fewer abstractions and more respect for fundamental web primitives.',
  0,
  now() - interval '5 days'
),
(
  6,
  'A Solo Hiker''s Guide to the Scottish Highlands in Autumn',
  'Travel',
  'Julian Ross',
  'user_julian',
  'There is an unvarnished honesty to the Scottish Highlands when October arrives. The summer crowds have vanished, midges are swept away by cold Atlantic gusts, and the heather transforms into a rich tapestry of ochre, bronze, and burnt orange.

Hiking alone in these ancient glens teaches you self-reliance. You quickly learn that waterproof gear is not a luxury, but a survival necessity.

My favorite stretch runs through Glen Affric—often called the most beautiful glen in Scotland. Native Scots pines stand like solitary sentinels beside mirror-still lochs. At night in a stone bothy, with the peat fire crackling and rain hammering the corrugated roof, you feel profoundly small, peaceful, and grounded.',
  'Navigating solitary trails, peat smoke, and golden bracken across Scotland''s most untamed wilderness.',
  0,
  now() - interval '4 days'
),
(
  7,
  'The Chemistry of Browning: Why Maillard Reactions Make Food Irresistible',
  'Cooking',
  'Devon Patel',
  'user_devon',
  'Why does seared steak smell so intoxicating compared to boiled meat? Why is the crusty heel of a baguette infinitely more flavorful than the soft interior crumb?

The answer is the Maillard reaction—a chemical cascade discovered in 1912 by French chemist Louis-Camille Maillard.

When amino acids and reducing sugars are exposed to dry heat above 140°C, hundreds of new flavor compounds are born. Savory, nutty, and caramelized aromas erupt.

To maximize this reaction in home cooking:
1. Always pat meats thoroughly dry with paper towels before searing. Moisture is the enemy of browning because water limits pan temperatures to 100°C.
2. Preheat heavy cast iron until it radiates heat.
3. Do not crowd the pan; steam will form and boil your food instead of searing it.',
  'Understanding the chemical magic behind caramelized crusts, golden roasted vegetables, and rich pan sauces.',
  0,
  now() - interval '3 days'
),
(
  8,
  'The Case for Single-Tasking: How Deep Focus Restores the Mind',
  'Lifestyle',
  'Clara Moreau',
  'user_clara',
  'Modern productivity culture sold us a lie: the belief that switching rapidly between Slack, terminal windows, text messages, and spreadsheets represents peak efficiency.

Neuroscience paints an entirely different picture. Cognitive scientists call the residual mental tax of switching tasks "attention residue." Each context shift leaves a fraction of your working memory stranded on the previous task.

Single-tasking is the deliberate practice of doing one thing at a time with full presence:
- When writing code, close the email client.
- When reading a book, leave your phone in another room.
- When conversing with a friend, keep both hands on the table.

You will find that your output quality skyrockets while your mental exhaustion plummets.',
  'Why modern multitasking exhausts our working memory and how mono-tasking restores deep cognitive endurance.',
  0,
  now() - interval '2 days'
),
(
  9,
  'Designing for Calm: Why Less Notification Noise Means Better Products',
  'Technology',
  'Alex Rivera',
  'user_alex',
  'Almost every modern web application is designed to scream at you. Red badge counters, unsolicited email digests, pop-up nudges, and urgent push alerts fight for every microsecond of your visual attention.

Growth engineers call this engagement. Users experience it as cognitive erosion.

Calm design takes the opposite stance:
1. Deliver value asynchronously without demanding immediate responses.
2. Provide peaceful default states with zero unprompted banners.
3. Allow users to finish a task and leave cleanly without algorithmic traps.

The most respected software tools of the next decade will be the ones that respect human dignity and allow users to do meaningful work without anxiety.',
  'How software interfaces can empower users through silence, clarity, and intentional restraint.',
  0,
  now() - interval '1 day'
),
(
  10,
  'The Books That Shaped How We See Cities',
  'Books',
  'Sarah Jenkins',
  'user_sarah',
  'A city is more than concrete, steel, and asphalt; it is an accretion of human desire, rhythm, and history. Literature gives us the eyes to perceive that invisible architecture.

In "The Death and Life of Great American Cities," Jane Jacobs introduced the concept of the "sidewalk ballet"—the spontaneous, intricate safety network created by active street life.

In Italo Calvino''s "Invisible Cities," Marco Polo describes imaginary metropolises that reflect human memory, desires, and grief.

When you walk down an urban street after reading these works, you stop seeing buildings as dead objects. You see a living organism shaped by collective human dreams.',
  'Exploring classic literature on urbanism, human psychology, and the hidden life of modern streetscapes.',
  0,
  now() - interval '6 hours'
);

-- Adjust sequence for posts table
SELECT setval(pg_get_serial_sequence('public.posts', 'id'), (SELECT MAX(id) FROM public.posts));

-- C. 25 Presentation-Ready Comments Linked to Real Users
INSERT INTO public.comments (post_id, author_id, author, content, created_at) VALUES
-- Post 1 (Slow Travel)
(1, 'user_sophia', 'Sophia Chen', 'The point about releasing itinerary pressure hits home. Staying in one neighborhood rather than city-hopping makes travel feel genuine rather than performative.', now() - interval '8 days'),
(1, 'user_liam', 'Liam Brooks', 'Florence is the ultimate city for this philosophy. Spending quiet afternoons reading in secluded cloister gardens gives the story real depth.', now() - interval '7 days'),
(1, 'user_clara', 'Clara Moreau', 'I did something similar in Lyon last spring. Slow travel genuinely rewired how I experience foreign cultures.', now() - interval '6 days'),

-- Post 2 (Sourdough)
(2, 'user_maya', 'Maya Lin', 'The Dutch oven steam crackle description is so vivid! The 72-hour cold retard completely changed my crumb open-structure as well.', now() - interval '7 days'),
(2, 'user_devon', 'Devon Patel', 'As a food science enthusiast, your explanation of temperature and enzymatic activity is spot on. Great guide!', now() - interval '6 days'),
(2, 'user_theo', 'Theo Van Dijk', 'Do you recommend 80% hydration for whole wheat blends or should beginners start at 70%?', now() - interval '5 days'),

-- Post 3 (Analog Mornings)
(3, 'user_sophia', 'Sophia Chen', 'Banishing screens before 9 AM doubled my attention span during morning lectures. Such a practical lifestyle experiment.', now() - interval '6 days'),
(3, 'user_marcus', 'Marcus Vance', 'The ritual of hand-grinding coffee beans as an analog anchor habit is brilliant. Inspiring read for students trying to reduce screen fatigue.', now() - interval '5 days'),
(3, 'user_hannah', 'Hannah Kim', 'I bought a manual alarm clock after reading this. Waking up without notifications feels like magic.', now() - interval '4 days'),

-- Post 4 (Rainy Train Books)
(4, 'user_liam', 'Liam Brooks', 'The Remains of the Day is an absolute masterpiece of emotional restraint. Perfect recommendation for an atmospheric train ride.', now() - interval '5 days'),
(4, 'user_maya', 'Maya Lin', 'Added In Praise of Shadows to my reading list immediately. Love this curated format!', now() - interval '4 days'),
(4, 'user_ananya', 'Ananya Sharma', 'A Month in the Country is criminally underrated. So glad you included J.L. Carr here.', now() - interval '3 days'),

-- Post 5 (Minimalist Developer)
(5, 'user_liam', 'Liam Brooks', 'As someone studying web development, the reminder to prioritize semantic HTML and core CSS over framework churn is so refreshing to read.', now() - interval '4 days'),
(5, 'user_elena', 'Elena Rostova', 'Durable architecture always wins long-term. This clearly demonstrates why foundational web primitives matter for clean code.', now() - interval '3 days'),
(5, 'user_alex', 'Alex Rivera', 'Every junior engineer needs to read this before downloading 50 npm dependencies.', now() - interval '2 days'),

-- Post 6 (Scottish Highlands)
(6, 'user_emma', 'Emma Watson', 'Glen Affric in autumn is breathtaking. Did you stay in the Strawberry Cottage bothy?', now() - interval '3 days'),
(6, 'user_zara', 'Zara Al-Mansoor', 'The photo descriptions alone make me want to pack a rucksack and head north. Beautiful writing Julian!', now() - interval '2 days'),

-- Post 7 (Maillard Reaction)
(7, 'user_sophia', 'Sophia Chen', 'Drying the meat surface with paper towels is the single best tip any amateur cook can learn. Night and day difference!', now() - interval '2 days'),
(7, 'user_oliver', 'Oliver Wright', 'Finally understood why my ground beef was boiling instead of browning—pan crowding was my mistake all along.', now() - interval '1 day'),

-- Post 8 (Single-Tasking)
(8, 'user_devon', 'Devon Patel', 'Attention residue is so real. Closing Slack tabs while coding improved my focus tremendously.', now() - interval '1 day'),
(8, 'user_sarah', 'Sarah Jenkins', 'Single-tasking feels rebellious in 2026, which makes it even more powerful.', now() - interval '18 hours'),

-- Post 9 (Designing for Calm)
(9, 'user_marcus', 'Marcus Vance', 'Calm software is the future. Users are completely fatigued by gamified notification loops.', now() - interval '14 hours'),
(9, 'user_theo', 'Theo Van Dijk', 'Products that respect user time build genuine long-term loyalty. Resonates 100%.', now() - interval '8 hours'),

-- Post 10 (Books on Cities)
(10, 'user_clara', 'Clara Moreau', 'Jane Jacobs sidewalk ballet passage completely changed how I look at my own neighborhood in Paris.', now() - interval '4 hours'),
(10, 'user_ananya', 'Ananya Sharma', 'Invisible Cities paired with street photography walks is pure bliss. Wonderful essay Sarah!', now() - interval '2 hours');

-- D. 56 Real Likes Linked 1:1 to Real Users
INSERT INTO public.likes (post_id, user_id) VALUES
-- Article 1 (5 Likes)
(1, 'user_sophia'),
(1, 'user_liam'),
(1, 'user_clara'),
(1, 'user_alex'),
(1, 'user_zara'),

-- Article 2 (6 Likes)
(2, 'user_maya'),
(2, 'user_liam'),
(2, 'user_emma'),
(2, 'user_devon'),
(2, 'user_theo'),
(2, 'user_ananya'),

-- Article 3 (7 Likes)
(3, 'user_sophia'),
(3, 'user_emma'),
(3, 'user_marcus'),
(3, 'user_julian'),
(3, 'user_sarah'),
(3, 'user_hannah'),
(3, 'user_oliver'),

-- Article 4 (5 Likes)
(4, 'user_maya'),
(4, 'user_sophia'),
(4, 'user_liam'),
(4, 'user_marcus'),
(4, 'user_clara'),

-- Article 5 (8 Likes)
(5, 'user_maya'),
(5, 'user_sophia'),
(5, 'user_emma'),
(5, 'user_elena'),
(5, 'user_devon'),
(5, 'user_alex'),
(5, 'user_theo'),
(5, 'user_ananya'),

-- Article 6 (4 Likes)
(6, 'user_maya'),
(6, 'user_liam'),
(6, 'user_oliver'),
(6, 'user_zara'),

-- Article 7 (6 Likes)
(7, 'user_sophia'),
(7, 'user_emma'),
(7, 'user_marcus'),
(7, 'user_julian'),
(7, 'user_hannah'),
(7, 'user_elena'),

-- Article 8 (5 Likes)
(8, 'user_liam'),
(8, 'user_clara'),
(8, 'user_sarah'),
(8, 'user_alex'),
(8, 'user_theo'),

-- Article 9 (6 Likes)
(9, 'user_marcus'),
(9, 'user_devon'),
(9, 'user_hannah'),
(9, 'user_oliver'),
(9, 'user_zara'),
(9, 'user_ananya'),

-- Article 10 (4 Likes)
(10, 'user_emma'),
(10, 'user_julian'),
(10, 'user_sarah'),
(10, 'user_elena');

-- Double check sync on posts.likes to match exact likes table count
UPDATE public.posts p
SET likes = (SELECT COUNT(*) FROM public.likes l WHERE l.post_id = p.id);
